spring:

  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: "Manchester@10"
  jpa:
    show-sql: true

websiteUrl: https://localhost:4242

